#!/usr/bin/env bash

. "$HOME/.bashrc"

APN="$1"

if [[ $APN"X" == "X" ]] ; then
  printf "%s \n"       " EX: bash /projects/MMA/mmcli-cl/connect-loop datacard.tre.it"
  printf "%s \n"       " EX: bash /projects/MMA/mmcli-cl/connect-loop mobile.vodafone.it"

  say "APN is needed as parameter .....  "
  exit
fi

## connect and autoreconnect
##
##
## (using mmcli 1.18.6)
## <massimo.manzato@gmail.com>

cd  /dev/shm/ || exit
wd=$(dirname $0)
cp "$wd/sites.list" .

. "$wd/mmcli_cl_functions"

#trap 'disconnectx' SIGINT SIGQUIT SIGABRT SIGKILL SIGTERM
#trap 'disconnectx' SIGINT SIGQUIT SgGABRT SIGTERM

	#rfkill unblock all
	#sleep 2
	#ifconfig wifi0 192.168.1.254/24 up

DEBUG="False"

im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
ib=$(mmcli -m "$im" |grep -m 1 "Bearer" |cut -d/ -f6)
declare -A arrayA="( $(mmcli -K --bearer $ib | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}' ) )"
#sv restart ModemManager
atime=$(date +%s)
printf "%s Initial checks, connected time : %s seconds [30s min refresh intervals]\n" "$(date +%T)" "${arrayA[bearer.stats.duration]}"
#connectx
#sleep 3

while true
do
	check
	if [[ ! $result == 'yes' ]]; then
		say "Check FAILED !! <---- "
		echo -n > /dev/shm/NOT-CONNECTED
		connectx "$APN"
		sleep 0.5
	fi

	im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
	ib=$(mmcli -m "$im" |grep -m 1 "Bearer" |cut -d/ -f6)
	declare -A arrayA="( $(mmcli -K --bearer $ib | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}' ) )"

	site1=$(shuf sites.list | head -1)
	testping=0
	site1="8.8.4.4"

	calc_RX_TX_seconds "${arrayA[bearer.status.interface]}"
	say_overwrite "BearerUpTime: ${arrayA[bearer.stats.duration]} | RX: $RXB | TX: $TXB        "
	#printf "BearerUpTime: |%s| \n" "${arrayA[bearer.stats.duration]}"

	## Se trasmetto ma non ricevo 
	if [ "$RXB" -eq 0 ] && [ "$TXB" -gt 0 ] ; then
		#sleep 1 &
		#wait $!
		say "Restart Bearer ${arrayA[bearer.properties.apn]} at : ${arrayA[bearer.stats.duration]} seconds "
		mmcli -b "$ib" -x
		say "Connect Bearer: ${arrayA[bearer.properties.apn]} "
		mmcli -b "$ib" -c
		say " ---> Start setup IP and Routes "
		setIPandROUTE
		say " ---> End setup IP and Routes "
		ib=$(mmcli -m "$im" |grep -m 1 "Bearer" |cut -d/ -f6)
		say "ping ISP DNS : ${arrayA[bearer.ipv4-config.dns.value[1]]}"
		ping_test " DNS: " "${arrayA[bearer.ipv4-config.dns.value[1]]}"
		if [ "$testping" -eq 0 ]; then
			say "TEST 2 - ping : $site1"
			ping_test "2" "$site1"
		fi

		if [ "$testping" -eq 0 ]; then
			site1="8.8.8.8"
			say "TEST 3 - ping : $site1"
			ping_test "3" "$site1"
		fi

		if [ "$testping" -gt 0 ] ||  [ "$RXB" -ne 0 ] ; then
			#printf "%s -  CONNECTED %s \n" "$(date +%T)" ""
			[[ -e /dev/shm/NOT-CONNECTED ]] && rm /dev/shm/NOT-CONNECTED
			sleep 0.2 &
			wait $!
		else
			#printf "\n%s time: %s  Testing.. %s: " "$(date +%T)" "${arrayA[bearer.stats.duration]}" "$site1"
			#printf "%s -  NOT Connected %s \n" "$(date +%T)" ""
			echo -n > /dev/shm/NOT-CONNECTED
			bearer -x
			sleep 0.2
		fi
	fi
done

