#!/bin/bash

## connect and autoreconnect 
## 
##
## (using mmcli 1.8.1)
## <massimo.manzato@gmail.com>

cd /tmp
cp /boot/scripts/sites.list .

. mmcli_cl_functions

#trap 'disconnectx' SIGINT SIGQUIT SIGABRT SIGKILL SIGTERM
trap 'disconnectx' SIGINT SIGQUIT SIGABRT SIGTERM

	#rfkill unblock all
	#sleep 2
	#ifconfig wifi0 192.168.1.254/24 up

sv restart ModemManager
atime=$(date +%s)
connectx
sleep 3

while true
do
	check
	if [[ ! $result == 'yes' ]]; then
		echo "not connected."
		echo -n > /dev/shm/NOT-CONNECTED
		connectx
		sleep 5
	fi

	echo -n "Testing.. "
	testping1=$(ping -4 -s 1 -c 6 -i 4 -W 4 -w 20  -n $(shuf sites.list | head -1) |grep "9 bytes" -c )
	testping2=$(ping -4 -s 1 -c 6 -i 4 -W 4 -w 20  -n $(shuf sites.list | head -1) |grep "9 bytes" -c )

	if [[ $testping1 -gt 0 || $testping2 -gt 0 ]]; then
		echo "connected."
		[[ -e /dev/shm/NOT-CONNECTED ]] && rm /dev/shm/NOT-CONNECTED
		sleep 40 &
		wait $!
	else
		echo "not connected."
		echo -n > /dev/shm/NOT-CONNECTED
		bearer -x
		sleep 1
	fi
done

