#!/bin/bash

## disconnect
## -- for my DirectIP-manual connection
##
## (using mmcli 1.18.6)
## <massimo.manzato@gmail.com>

. mmcli_cl_functions

isModemNotExists && echo "No any modem !" && exit

im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
pid=$(ps ax |grep "[s]udo /project/MMA/mmcli-cl/connect-loop" |awk '{print $1}')

if [[ ! -z "$pid" ]]; then
	kill -s 2 "$pid"
	echo "Disconnecting.."
	exit
fi

echo "Process not exists."
echo ">> Trying basic method.."
scpid=$(pgrep "etup-connection")
[[ ! -z "$scpid" ]] && kill -s 15 "$scpid"
pkill ping
bearer -x
mmcli -m "$im" --simple-disconnect
sleep 2
mmcli -m "$im" -d
	#mmcli -m "$im" --command=AT+CFUN=0
sleep 2
ip r d default 
sleep 2
## systemctl stop squid
mmcli -m "$im" -r
#systemctl restart ModemManager
sv restart ModemManager

