#!/bin/bash

## disconnect
## -- for my DirectIP-manual connection
##
## (using mmcli 1.18.6)
## <massimo.manzato@gmail.com>

wd=$(dirname $0)
cp "$wd/sites.list" .

. "$wd/mmcli_cl_functions"

isModemNotExists && echo "No any modem !" && exit

im=$(mmcli --list-modems |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
pid=$(ps ax |grep "connect-loop" |awk '{print $1}')

if [[ ! -z "$pid" ]]; then
	cmd_or_print kill -s 2 "$pid"
	say "Disconnecting.."
	exit
fi

say "Process not exists."
say ">> Trying basic method.."
scpid=$(pgrep "etup-connection")
[[ ! -z "$scpid" ]] && kill -s 15 "$scpid"
cmd_or_print pkill ping
cmd_or_print bearer --disconnect
cmd_or_print mmcli --modem="$im" --simple-disconnect
cmd_or_print sleep 2
cmd_or_print mmcli --modem="$im" --disable
cmd_or_print sleep 2
cmd_or_print ip r d default
cmd_or_print ip -6 r d default
cmd_or_print sleep 2
cmd_or_print mmcli --modem="$im" --reset
cmd_or_print sv restart ModemManager

