#!/bin/bash

## mmcli-cl functions 
## -- for my Modem DirectIP-manual connection
##
## (using mmcli 1.18.6)
	## <massimo.manzato@gmail.com>

wd=$(dirname "$0")

function say() {
    #printf "\n[$(date --iso-8601=seconds)] %b\n" "$1"
    printf "[$(date '+%Y-%m-%d %T')] %b\n" "$1"
    }

function say_overwrite() {
    #printf "\n[$(date --iso-8601=seconds)] %b\n" "$1"
    printf "\033[0K\r[$(date '+%Y-%m-%d %T')] %b" "$1"
    }


function cmd_or_print() { # command
    if [ "$DEBUG" == "True" ] ;then
          say "'$*'"
    fi
    "$@" || say "Failed at: '$*'"
    }

function datetime()
{
	date +"%A, %-d %B %Y - %T %Z"
}

function calc_RX_TX_seconds()
{
          IFN="$1"
          BR1=$(cat /sys/class/net/"${IFN}"/statistics/rx_bytes)
          BT1=$(cat /sys/class/net/"${IFN}"/statistics/tx_bytes)
          sleep 1
          BR2=$(cat /sys/class/net/"${IFN}"/statistics/rx_bytes)
          BT2=$(cat /sys/class/net/"${IFN}"/statistics/tx_bytes)
          TXB=$((BT2 - BT1))
          RXB=$((BR2 - BR1))
}

function ping_test()
{
	TESTNUM=$1
	site=$2

	timestartping="$(date +%T)"
	testping=$(ping -4 -s 1 -c 1 -W 1 -n "$site" | grep "9 bytes" -c )

	if [ "$testping" -eq 0 ]  ; then
		printf "\nTEST%s started at: %s ___ finished at: %s  Bearer Duration: %s Testing site: %s  --- FAILED\n" "$TESTNUM" "$timestartping" "$(date +%T)" "${arrayA[bearer.stats.duration]}" "$site"
	fi
}

function isModemNotExists()
{
		local modm
		modm=$(mmcli --list-modems | grep -m 1 "Modem")
		[[ -z "$modm" ]] && return 0
		return 1
}

function bearer()
{
		local ib
		ib=$(mmcli --modem="$im" |grep -m 1 "Bearer" |cut -d/ -f6)
		[[ -z "$ib" ]] && echo "No any bearer." && return 1

		#say "execute: -->> mmcli --modem=$im --bearer=$ib $@ <<--"
		cmd_or_print mmcli --modem="$im" --bearer="$ib" "$@"
		return 0
}

function check()
{

 		im=$(mmcli --list-modems |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
		local ib
		ib=$(mmcli --modem="$im" |grep -m 1 "Bearer" |cut -d/ -f6)
		declare -A arrayA="( $(mmcli --output-keyvalue --bearer $ib | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}' ) )"
		result="${arrayA[bearer.status.connected]}"
}

function setIPandROUTE()
{
		local ib=$(mmcli --modem="$im" |grep -m 1 "Bearer" |cut -d/ -f6)
		declare -A arrayA="( $(mmcli --output-keyvalue --bearer $ib | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}' ) )"

		cmd_or_print ip link set up dev "${arrayA[bearer.status.interface]}"

		# remove the actual ip on interface
		cmd_or_print ip a flush "${arrayA[bearer.status.interface]}"
		cmd_or_print ip a replace "${arrayA[bearer.ipv4-config.address]}/${arrayA[bearer.ipv4-config.prefix]}" dev "${arrayA[bearer.status.interface]}"
		cmd_or_print ip r a default via "${arrayA[bearer.ipv4-config.gateway]}"

		case "$IPTYPE" in
     ipv4v6|ipv6)
     # Do stuff
		   cmd_or_print ip -6 a replace "${arrayA[bearer.ipv6-config.address]}/${arrayA[bearer.ipv6-config.prefix]}" dev "${arrayA[bearer.status.interface]}"
		   cmd_or_print ip -6 r a default via "${arrayA[bearer.ipv6-config.gateway]}"
     ;;
    esac
}

function isNetworkFailed()
{
		local state
		state=$(mmcli --modem="$im" | grep -m 1 state | awk '{print $3}' | cut -d\' -f2)
		[[ "$state" == 'registered' ]] && return 1
		return 0
}

function disconnectx()
{
		echo "Disconnecting.."
		local scpid
		scpid=$(pgrep "etup-connection")
			#echo scpid=$scpid
		[[ -n "$scpid" ]] && kill -s 15 "$scpid" && echo Cancelled.
		pkill ping
		echo -n > /dev/shm/NOT-CONNECTED
		cmd_or_print bearer --disconnect
		cmd_or_print mmcli --modem="$im" --simple-disconnect
		cmd_or_print ip r d default
		cmd_or_print ip -6 r d default

		#This disconnects the existing connection(s) for the modem and puts it into a low power mode
		cmd_or_print mmcli --modem="$im" --disable
		sleep 2

		#Resets the modem to the settings it had when it was power cycled. 
		cmd_or_print mmcli --modem="$im" --reset
		sleep 1
		cmd_or_print sv restart ModemManager
		datetime
		btime=$(date +%s)
		exit
}

function connectx()
{
		say "Start setup-connection scripts..."
		"$wd/setup-connection" "$APN" "$IPTYPE" &
			   #scpid=$!
		wait $!
		scpid=
		im=$(mmcli --list-modems |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
}

