#!/bin/bash

wd=$(dirname "$0")
cp "$wd/sites.list" .

. "$wd/mmcli_cl_functions"

APN="$1"

## setup connection
## -- for my Modem DirectIP-manual connection
##
## (using mmcli 1.18.6)
## <massimo.manzato@@gmail.com>

datetime

say ">> Waiting for modem.."
say -n "please wait"
while true
do
	echo -n "."
	! isModemNotExists && break
	sleep 1
done
echo

im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')

say ">> Resetting.."
bearer -x
ip r d default
echo
#mmcli -m "$im" --set-allowed-modes='any'
#mmcli -m "$im" --set-allowed-modes='4g'
#mmcli -m "$im" --set-allowed-modes='3g'

	#echo ">> Registering to home network.."
	#mmcli -m $im --3gpp-register-home
	#sleep 5

	#isNetworkFailed && exit

#sleep 1

say ">> Checking bearer.."
#declare -A a="( $(mmcli -m "$im" -K ) )"
declare -A arrayM="( $(mmcli -m "$im" -K | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}') )"
	#[[ $a == 1 ]] && mmcli -m $im --create-bearer="apn=3data,number=*99#,user=3data,password=3data,allow-roaming=1,ip-type=ipv4,allowed-auth=eap|pap|chap" || echo "Bearer already exist."
#[[ "$a" == 1 ]] && mmcli -m "$im" --create-bearer="apn=indosatgprs,number=*99#,user=indosat,password=indosat,allow-roaming=1,ip-type=ipv4,allowed-auth=eap|pap|chap" || echo "Bearer already exist."
if [ "$((${arrayM[modem.generic.bearers.length]}))" -gt 0 ] ; then
	say "Already exist Bearer: "
	say "${arrayM[modem.generic.bearers.value[1]]}"
else
	#mmcli -m "$im" --create-bearer="apn=mobile.vodafone.it"
	say ">> Creating bearer: apn=${APN}"
	cmd_or_print mmcli -m "$im" --create-bearer="apn=${APN}"
fi

say ">> Connecting.."
try=0
im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')
ib=$(mmcli -m "$im" |grep -m 1 "Bearer" |cut -d/ -f6)
declare -A arrayA="( $(mmcli -K --bearer $ib | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}' ) )"
sleep 1
say "----> Connecting Bearer: ${arrayA[bearer.properties.apn]}"
! bearer -c && exit

while true
do
	sleep 1
	check
	if [ "$result" == 'yes' ]; then
		say 'success.'
		break
	else
		# patch when modem unplugged
		isModemNotExists && exit

		# give up (and then restart again)
		[[ "$try" == 4 ]] && exit

		((try++))
		say "failed. Trying again.. ($try)"

		say ">> Connecting.. in while"
		say ">> Connecting.. in a while : ${arrayA[bearer.properties.apn]}"
		sleep 1
		! bearer -c && exit
	fi
done

#sleep 2

say ">> Enabling Modem signal-setup"
DEBUG="True" cmd_or_print mmcli -m "$im" --signal-setup=2

say ">> Setup wwan interface and default route."
setIPandROUTE

