#!/bin/bash

wd=$(dirname $0)
cp "$wd/sites.list" .

. "$wd/mmcli_cl_functions"

## setup connection
## -- for my Modem DirectIP-manual connection
##
## (using mmcli 1.18.6)
## <massimo.manzato@@gmail.com>

datetime

echo ">> Waiting for modem.."
echo -n "please wait"
while true
do
	echo -n "."
	! isModemNotExists && break
	sleep 1
done
echo

im=$(mmcli -L |grep -m 1 "Modem" |cut -d/ -f6 |awk '{print $1}')

echo ">> Resetting.."
bearer -x
ip r d default
echo

echo ">> Enabling modem.."
mmcli -m "$im" --signal-setup=2
#mmcli -m "$im" --set-allowed-modes='any'
#mmcli -m "$im" --set-allowed-modes='4g'
#mmcli -m "$im" --set-allowed-modes='3g'

	#echo ">> Registering to home network.."
	#mmcli -m $im --3gpp-register-home
	#sleep 5

	#isNetworkFailed && exit

#sleep 1

echo ">> Creating bearer.."
#declare -A a="( $(mmcli -m "$im" -K ) )"
declare -A arrayM="( $(mmcli -m "$im" -K | awk '{ printf "[\"%s\"]=\"%s\" ", $1, $3}') )"
	#[[ $a == 1 ]] && mmcli -m $im --create-bearer="apn=3data,number=*99#,user=3data,password=3data,allow-roaming=1,ip-type=ipv4,allowed-auth=eap|pap|chap" || echo "Bearer already exist."
#[[ "$a" == 1 ]] && mmcli -m "$im" --create-bearer="apn=indosatgprs,number=*99#,user=indosat,password=indosat,allow-roaming=1,ip-type=ipv4,allowed-auth=eap|pap|chap" || echo "Bearer already exist."
if [ "${arrayM[modem.generic.bearers.length]}" -gt 0 ] ; then
	echo "Bearer already exist."
	echo "${arrayM[modem.generic.bearers.value[1]]}"
else
	mmcli -m "$im" --create-bearer="apn=mobile.vodafone.it"
	#mmcli -m "$im" --create-bearer="apn=datacard.tre.it"
fi

echo ">> Connecting.."
try=0
sleep 3
! bearer -c && exit

while true
do
	sleep 1
	check
	if [ "$result" == 'yes' ]; then
		echo 'success.'
		break
	else
		# patch when modem unplugged
		isModemNotExists && exit

		# give up (and then restart again)
		[[ "$try" == 4 ]] && exit

		((try++))
		echo "failed. Trying again.. ($try)"

		echo ">> Connecting.. in while"
		sleep 7
		! bearer -c && exit
	fi
done

sleep 2

echo ">> Setup wwan interface and default route."
setIPandROUTE


